# Generated by Django 3.1 on 2020-09-07 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن همراه')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('birth_month', models.CharField(choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=10, verbose_name='ماه تولد')),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300)], verbose_name='سال تولد')),
                ('birth_day', models.IntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='روز تولد')),
                ('city', models.CharField(max_length=30, verbose_name='شهر محل سکونت')),
                ('education', models.CharField(choices=[('دبستان', 'دبستان'), ('پایه هفتم', 'پایه هفتم'), ('پایه هشتم', 'پایه هشتم'), ('پایه نهم', 'پایه نهم'), ('پایه دهم', 'پایه دهم'), ('پایه یازدهم', 'پایه یازدهم'), ('پایه دوازدهم', 'پایه دوازدهم'), ('دانشجوی کارشناسی', 'دانشجوی کارشناسی'), ('دانشجوی کارشناسی ارشد', 'دانشجوی کارشناسی ارشد'), ('دانشجوی دکتری', 'دانشجوی دکتری'), ('شاغل', 'شاغل')], max_length=30, verbose_name='پایه/مقطع تحصیلی')),
                ('organization', models.CharField(max_length=50, verbose_name='نام مدرسه/دانشگاه/محل کار')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('is_vip', models.BooleanField(default=False, verbose_name='کاربر ویژه (می تواند تمام مقالات را بخواند)')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر ادمین باشد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کاربر می تواند وارد صفحه ادمین شود')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='کاربر می تواند به تمام محتواهای سایت دسترسی داشته و آنها را تغییر دهد')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
