# Generated by Django 3.1 on 2020-09-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200907_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='field',
            field=models.CharField(default='', max_length=50, verbose_name='رشته تحصیلی'),
            preserve_default=False,
        ),
    ]
