# Generated by Django 3.1 on 2020-09-07 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='روز تولد'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_month',
            field=models.CharField(blank=True, choices=[('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور'), ('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند')], max_length=10, null=True, verbose_name='ماه تولد'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300)], verbose_name='سال تولد'),
        ),
    ]
