# Generated by Django 3.1 on 2020-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content1',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content2',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content3',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content4',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content5',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
