# Generated by Django 3.1 on 2020-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200827_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image5',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(default=None, upload_to='static/articles/images'),
            preserve_default=False,
        ),
    ]
