# Generated by Django 3.1 on 2020-08-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200827_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='content3',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='content4',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='content5',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='static/articles/images'),
        ),
    ]
