# Generated by Django 3.1 on 2020-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200827_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
    ]
