# Generated by Django 3.1 on 2020-08-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200827_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='articles/static/articles/images'),
        ),
    ]
