# Generated by Django 3.1 on 2020-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200827_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
