# Generated by Django 3.1 on 2020-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200827_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=100, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content1',
            field=models.TextField(verbose_name='قسمت اول محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=models.TextField(blank=True, verbose_name='قسمت دوم محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content3',
            field=models.TextField(blank=True, verbose_name='قسمت سوم محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content4',
            field=models.TextField(blank=True, verbose_name='قسمت چهارم محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content5',
            field=models.TextField(blank=True, verbose_name='قسمت پنجم محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس اول'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس دوم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس سوم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس چهارم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس پنجم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان مقاله'),
        ),
    ]
