# Generated by Django 3.1 on 2020-09-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200904_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='مقالات',
        ),
    ]
