# Generated by Django 3.1 on 2020-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200904_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
    ]
