# Generated by Django 3.1 on 2020-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upl',
            field=models.FileField(upload_to='file_main_file'),
        ),
    ]
