# Generated by Django 3.1 on 2020-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200825_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_upl',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
