# Generated by Django 3.1 on 2020-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20200827_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.FileField(upload_to='archive/pdfs/'),
        ),
    ]
