# Generated by Django 3.1 on 2020-09-04 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20200828_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'نشریه', 'verbose_name_plural': 'نشریات'},
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='Title',
        ),
        migrations.AddField(
            model_name='pdf',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(default='', max_length=800, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_url',
            field=models.FileField(upload_to='archive/audios/', verbose_name='آپلود فایل'),
        ),
    ]
