# Generated by Django 3.1 on 2020-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=800)),
                ('Creator', models.CharField(max_length=100)),
                ('Date', models.DateField(verbose_name=models.DateField(verbose_name='تاریخ انتشار:'))),
                ('file_url', models.FileField(upload_to='archive/pdfs/')),
            ],
        ),
    ]
