# Generated by Django 3.1 on 2020-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofoqSchool', '0002_auto_20200828_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='عنوان')),
                ('creator', models.CharField(max_length=100, verbose_name='ایجادکننده')),
                ('date', models.DateField(verbose_name='تاریخ انتشار:')),
                ('file_url', models.FileField(upload_to='archive/audios/', verbose_name='آپلود فایل')),
            ],
            options={
                'verbose_name': 'فایل صوتی',
                'verbose_name_plural': 'فایل های صوتی',
            },
        ),
        migrations.DeleteModel(
            name='Audio_File',
        ),
    ]
