# Generated by Django 3.1 on 2020-09-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofoqSchool', '0003_auto_20200904_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ انتشار:'),
        ),
    ]
